name: Generate API clients
on: 
  repository_dispatch:
    types: [openapi-update]

env:
  OPENAPI_URL: https://raw.githubusercontent.com/Apicurio/apicurio-registry/master/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json

jobs:
  generate_go:
    name: Generate Go client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: craicoverflow/openapi-generator-action@v1
        with:
          generator: go
          input: ${OPENAPI_URL}
          git-repo-id: registry-sdk-go
          git-user-id: Apicurio
          package-name: registry
          output: client

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'client/**'
      
      - name: Stage source files
        if: steps.changes.outputs.src == 'true'
        run: git add client/**

      
      - name: Create Pull Request
        if: steps.changes.outputs.src == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          branch-suffix: short-commit-hash
          branch: generate-sdk
