name: Generate API clients
on: 
  push:
    branches:
      - poc

env:
  OPENAPI_URL: https://raw.githubusercontent.com/Apicurio/apicurio-registry/master/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json

jobs:
  generate_go:
    name: Generate Go client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: craicoverflow/openapi-generator-action@v1
        with:
          generator: go
          input: ${OPENAPI_URL}
          output: go

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - 'go/**'

      - name: Commit changes
        if: steps.changes.outputs.go == 'true'
        uses: EndBug/add-and-commit@v8
        with:
          add: 'go'
          message: 'Update Go client'

